TypeScript Conversion
azanbinzahid/job-portal pull request #37
Opened 2020-08-07 09:09 UTC by azanbinzahid

2020-08-18 11:31 UTC, ahsanbilalas requested changes

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/package.json
> +    "@types/yup": "^0.29.4",
typescript is used in development process so please try to keep @types definitions in development dependencies.

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/AlertBox.tsx
> +const AlertBox = (props: Props) => {
this is not the way of assigning the type definitions to react component. please assign the type definition to component like this 
const AlertBox:FC<Props> = (props) => {

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/AlertBox.tsx
> +        )
can you please make sure that code is properly linted using eslint, prettier vs code ? if not then please implement the eslint, prettier integration with app.

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/EditProfileForm.tsx
> +const EditProfileForm = (props: Props) => {
Please implement the typescript validation as explained in AlertBox

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/EditProfileForm.tsx
> +        <Form onSubmit={(e: React.FormEvent<HTMLFormElement>)=>handleSubmit(e)}>
seems like lint issue here (e: React.FormEvent<HTMLFormElement>)=>handleSubmit(e)}

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/EditProfileForm.tsx
> +            {errors.firstName}
we can create a separate/generic component for text field, which can implemented with all its related operations like label, error messages and field. through this way, the field format will be same and label & error message will need not to manage in each component separately in whole app. and to utilize the component we can use the code as below
```
<TextField
label="First Name"
 name="firstName"
placeholder="First Name"
value={values.firstName}
onChange={handleChange}
error={errors.firstName}

/>
```

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/Home.tsx
> +const Home = (props: Props) => {
simplify the props object in component by using the object structure 
```
const Home:FC<Props> = ({ firstName, isLogged, jobCount  }) => {
```

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/JobItem.tsx
> +export default JobItem;
add the line break on line 52/53.

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/JobList.tsx
> +            <JobItem key={job.id} job={job}/>
this map will through the exception if the jobs will have the null or undefined data. so its preferred to apply condition before iterating through map

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/Login.tsx
> +        <Jumbotron <React.ElementType> align="center">
whats the impact of <React.ElementType> in <Jumbotron <React.ElementType> align="center>

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/NavBar.tsx
> +const Item = styled.h4``;
please remove the Item and use the h4 where Item is being used. Item is seems useless because h4 style is empty

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/NavBar.tsx
> +          />{ <Title>  Job Portal</Title> }
There is no need of braces {} with Title. please remvoe it

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/components/SingleJob.tsx
> +    console.log(jobId)
please remove the console.log from code. never commit it to git

2020-08-18 11:31 UTC, ahsanbilalas commented on tsfrontend/src/redux/reducers/alertReducer.tsx
> +        case "SET_ALERT":
please use enum definition here for SET alert
AlertActionTypes.SET_ALERT.
I think its defined in code. avoid using string here to keep the things generic

2020-08-19 09:00 UTC, azanbinzahid commented on tsfrontend/src/components/EditProfileForm.tsx
> +        <Form onSubmit={(e: React.FormEvent<HTMLFormElement>)=>handleSubmit(e)}>
I have enabled linting but it accepts FormEvent with <HTMLFormElement>

2020-08-19 09:07 UTC, azanbinzahid commented on tsfrontend/src/components/Login.tsx
> +        <Jumbotron <React.ElementType> align="center">
Without writing this, it does not accept "align" keyword

2020-08-21 11:04 UTC, merged